version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.1
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:22888:23888
  kafka:
    image: confluentinc/cp-kafka:3.0.1
    ports:
      - "19092:19092"
    depends_on:
        - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:19092